## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file /home/archdoc/git-repos/AAG-College-Algebra/buildExams/Module5B.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_34 = Integer(34); _sage_const_39 = Integer(39); _sage_const_45 = Integer(45); _sage_const_5 = Integer(5); _sage_const_21 = Integer(21); _sage_const_49 = Integer(49); _sage_const_67 = Integer(67); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_69 = Integer(69); _sage_const_22 = Integer(22); _sage_const_73 = Integer(73); _sage_const_85 = Integer(85)## This file (Module5B.sagetex.sage) was *autogenerated* from Module5B.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module5B', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_34 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
 keyFileName = "Module5"
 version = "B"
except:
 _st_.goboom(_sage_const_39 )
_st_.blockend()
_st_.current_tex_line = _sage_const_45 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_5 
 problemNumber=_sage_const_21 
 load("../Code/radical/radicalGraphToEquation.sage")
except:
 _st_.goboom(_sage_const_49 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_1 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_2 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_67 )
_st_.current_tex_line = _sage_const_69 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_5 
 problemNumber=_sage_const_22 
 load("../Code/radical/domainRadical.sage")
except:
 _st_.goboom(_sage_const_73 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_85 
 _st_.inline(_sage_const_5 , latex(displayStem))
except:
 _st_.goboom(_sage_const_85 )

