## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file /home/archdoc/git-repos/AAG-College-Algebra/buildExams/Module6A.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_34 = Integer(34); _sage_const_39 = Integer(39); _sage_const_45 = Integer(45); _sage_const_6 = Integer(6); _sage_const_26 = Integer(26); _sage_const_49 = Integer(49); _sage_const_62 = Integer(62); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_64 = Integer(64); _sage_const_27 = Integer(27); _sage_const_68 = Integer(68); _sage_const_85 = Integer(85); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_87 = Integer(87); _sage_const_28 = Integer(28); _sage_const_91 = Integer(91); _sage_const_104 = Integer(104); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_18 = Integer(18); _sage_const_106 = Integer(106); _sage_const_29 = Integer(29); _sage_const_110 = Integer(110); _sage_const_125 = Integer(125); _sage_const_19 = Integer(19); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_24 = Integer(24); _sage_const_127 = Integer(127); _sage_const_30 = Integer(30); _sage_const_131 = Integer(131); _sage_const_148 = Integer(148); _sage_const_25 = Integer(25)## This file (Module6A.sagetex.sage) was *autogenerated* from Module6A.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module6A', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_34 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
 keyFileName = "Module6"
 version = "A"
except:
 _st_.goboom(_sage_const_39 )
_st_.blockend()
_st_.current_tex_line = _sage_const_45 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_6 
 problemNumber=_sage_const_26 
 load("../Code/polynomial/constructPolyComplex.sage")
except:
 _st_.goboom(_sage_const_49 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_1 , latex(displayZero1))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_2 , latex(displayZero2))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_6 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_7 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_62 )
_st_.current_tex_line = _sage_const_64 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_6 
 problemNumber=_sage_const_27 
 load("../Code/polynomial/polyEndBehavior.sage")
except:
 _st_.goboom(_sage_const_68 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_85 
 _st_.inline(_sage_const_8 , latex(displayStem))
except:
 _st_.goboom(_sage_const_85 )
try:
 _st_.current_tex_line = _sage_const_85 
 _st_.inline(_sage_const_9 , latex(displayPolynomial))
except:
 _st_.goboom(_sage_const_85 )
_st_.current_tex_line = _sage_const_87 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_6 
 problemNumber=_sage_const_28 
 load("../Code/polynomial/constructPolyRationals.sage")
except:
 _st_.goboom(_sage_const_91 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_10 , latex(displayStem))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_11 , latex(displayZero1))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_12 , latex(displayZero2))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_13 , latex(displayZero3))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_14 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_15 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_16 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_17 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_18 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_104 )
_st_.current_tex_line = _sage_const_106 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_6 
 problemNumber=_sage_const_29 
 load("../Code/polynomial/polyGraphToFunction.sage")
except:
 _st_.goboom(_sage_const_110 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.inline(_sage_const_19 , latex(displayStem))
except:
 _st_.goboom(_sage_const_125 )
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.inline(_sage_const_20 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_125 )
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.inline(_sage_const_21 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_125 )
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.inline(_sage_const_22 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_125 )
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.inline(_sage_const_23 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_125 )
try:
 _st_.current_tex_line = _sage_const_125 
 _st_.inline(_sage_const_24 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_125 )
_st_.current_tex_line = _sage_const_127 
_st_.blockbegin()
try:
 moduleNumber=_sage_const_6 
 problemNumber=_sage_const_30 
 load("../Code/polynomial/polyZeroBehavior.sage")
except:
 _st_.goboom(_sage_const_131 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_25 , latex(displayStem))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_26 , latex(displayPolynomial))
except:
 _st_.goboom(_sage_const_148 )
_st_.endofdoc()

