## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file /home/archdoc/git-repos/AAG-College-Algebra/buildExams/Module6B.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_66 = Integer(66); _sage_const_41 = Integer(41); _sage_const_131 = Integer(131); _sage_const_89 = Integer(89); _sage_const_47 = Integer(47); _sage_const_113 = Integer(113); _sage_const_87 = Integer(87); _sage_const_68 = Integer(68); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_30 = Integer(30); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_35 = Integer(35); _sage_const_51 = Integer(51); _sage_const_108 = Integer(108); _sage_const_109 = Integer(109); _sage_const_126 = Integer(126); _sage_const_127 = Integer(127); _sage_const_72 = Integer(72); _sage_const_93 = Integer(93); _sage_const_144 = Integer(144)## This file (Module6B.sagetex.sage) was *autogenerated* from Module6B.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module6B', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
 load("../Code/commonlyUsedFunctions.sage")
 keyFileName = "Module6"
 version = "B"
except:
 _st_.goboom(_sage_const_41 )
_st_.blockend()
_st_.current_tex_line = _sage_const_47 
_st_.blockbegin()
try:
 moduleNumber="6"
 problemNumber=_sage_const_26 
 load("../Code/06polynomial/polyZeroBehavior.sage")
except:
 _st_.goboom(_sage_const_51 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_1 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_66 )
_st_.current_tex_line = _sage_const_68 
_st_.blockbegin()
try:
   moduleNumber="6"
   problemNumber=_sage_const_27 
   load("../Code/06polynomial/polyGraphToFunction.sage")
   
except:
 _st_.goboom(_sage_const_72 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_2 , latex(displayStem))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_6 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_7 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_87 )
_st_.current_tex_line = _sage_const_89 
_st_.blockbegin()
try:
 moduleNumber="6"
 problemNumber=_sage_const_28 
 load("../Code/06polynomial/polyEndBehavior.sage")
except:
 _st_.goboom(_sage_const_93 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_8 , latex(displayStem))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_9 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_108 )
_st_.current_tex_line = _sage_const_109 
_st_.blockbegin()
try:
 moduleNumber="6"
 problemNumber=_sage_const_29 
 load("../Code/06polynomial/constructPolyRationals.sage")
except:
 _st_.goboom(_sage_const_113 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_10 , latex(displayStem))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_11 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_12 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_13 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_14 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_15 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_16 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_126 )
_st_.current_tex_line = _sage_const_127 
_st_.blockbegin()
try:
 moduleNumber="6"
 problemNumber=_sage_const_30 
 load("../Code/06polynomial/constructPolyComplex.sage")
except:
 _st_.goboom(_sage_const_131 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_17 , latex(displayStem))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_18 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_19 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_20 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_21 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_22 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_23 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_144 )
_st_.endofdoc()

