## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file /home/archdoc/git-repos/AAG-College-Algebra/buildExams/Module12MC.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_31 = Integer(31); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_59 = Integer(59); _sage_const_30 = Integer(30); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_66 = Integer(66); _sage_const_41 = Integer(41); _sage_const_110 = Integer(110); _sage_const_131 = Integer(131); _sage_const_89 = Integer(89); _sage_const_60 = Integer(60); _sage_const_47 = Integer(47); _sage_const_87 = Integer(87); _sage_const_68 = Integer(68); _sage_const_114 = Integer(114); _sage_const_33 = Integer(33); _sage_const_150 = Integer(150); _sage_const_135 = Integer(135); _sage_const_32 = Integer(32); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_58 = Integer(58); _sage_const_57 = Integer(57); _sage_const_56 = Integer(56); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_35 = Integer(35); _sage_const_51 = Integer(51); _sage_const_108 = Integer(108); _sage_const_72 = Integer(72); _sage_const_93 = Integer(93); _sage_const_129 = Integer(129); _sage_const_14 = Integer(14)## This file (Module12MC.sagetex.sage) was *autogenerated* from Module12MC.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module12MC', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
 load("../Code/commonlyUsedFunctions.sage")
 keyFileName = "Module12M"
 version = "C"
except:
 _st_.goboom(_sage_const_41 )
_st_.blockend()
_st_.current_tex_line = _sage_const_47 
_st_.blockbegin()
try:
   moduleNumber="12M"
   problemNumber=_sage_const_56 
   load("../Code/12solvingWordProblems/identifyModelGraph12.sage")
   
except:
 _st_.goboom(_sage_const_51 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_1 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_2 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_66 )
_st_.current_tex_line = _sage_const_68 
_st_.blockbegin()
try:
 moduleNumber="12M"
 problemNumber=_sage_const_57 
 load("../Code/12solvingWordProblems/constructModelMixed.sage")
except:
 _st_.goboom(_sage_const_72 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_6 , latex(displayStem))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_7 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_8 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_9 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_10 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_11 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_12 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_87 )
_st_.current_tex_line = _sage_const_89 
_st_.blockbegin()
try:
 moduleNumber="12M"
 problemNumber=_sage_const_58 
 load("../Code/12solvingWordProblems/solveModelExp.sage")
except:
 _st_.goboom(_sage_const_93 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_13 , latex(displayStem))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_14 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_15 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_16 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_17 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_18 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_19 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_108 )
_st_.current_tex_line = _sage_const_110 
_st_.blockbegin()
try:
 moduleNumber="12M"
 problemNumber=_sage_const_59 
 load("../Code/12solvingWordProblems/solveModelPower.sage")
except:
 _st_.goboom(_sage_const_114 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_20 , latex(displayStem))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_21 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_22 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_23 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_24 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_25 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_26 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_129 )
_st_.current_tex_line = _sage_const_131 
_st_.blockbegin()
try:
 moduleNumber="12M"
 problemNumber=_sage_const_60 
 load("../Code/12solvingWordProblems/solveModelLinear.sage")
except:
 _st_.goboom(_sage_const_135 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_27 , latex(displayStem))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_28 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_29 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_30 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_31 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_32 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_33 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_150 )
_st_.endofdoc()

