## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file /home/archdoc/git-repos/AAG-College-Algebra/buildExams/Module11MC.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_55 = Integer(55); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_66 = Integer(66); _sage_const_41 = Integer(41); _sage_const_137 = Integer(137); _sage_const_54 = Integer(54); _sage_const_131 = Integer(131); _sage_const_89 = Integer(89); _sage_const_133 = Integer(133); _sage_const_47 = Integer(47); _sage_const_37 = Integer(37); _sage_const_53 = Integer(53); _sage_const_110 = Integer(110); _sage_const_116 = Integer(116); _sage_const_68 = Integer(68); _sage_const_34 = Integer(34); _sage_const_33 = Integer(33); _sage_const_152 = Integer(152); _sage_const_40 = Integer(40); _sage_const_32 = Integer(32); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_35 = Integer(35); _sage_const_52 = Integer(52); _sage_const_51 = Integer(51); _sage_const_36 = Integer(36); _sage_const_39 = Integer(39); _sage_const_72 = Integer(72); _sage_const_91 = Integer(91); _sage_const_38 = Integer(38); _sage_const_95 = Integer(95); _sage_const_112 = Integer(112)## This file (Module11MC.sagetex.sage) was *autogenerated* from Module11MC.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module11MC', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
 load("../Code/commonlyUsedFunctions.sage")
 keyFileName = "Module11M"
 version = "C"
except:
 _st_.goboom(_sage_const_41 )
_st_.blockend()
_st_.current_tex_line = _sage_const_47 
_st_.blockbegin()
try:
 moduleNumber="11M"
 problemNumber=_sage_const_51 
 load("../Code/11modelingLogExp/constructBacteriaGrowth.sage")
except:
 _st_.goboom(_sage_const_51 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_1 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_2 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_6 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_66 )
_st_.current_tex_line = _sage_const_68 
_st_.blockbegin()
try:
   moduleNumber="11M"
   problemNumber=_sage_const_52 
   load("../Code/11modelingLogExp/identifyModelPopulation.sage")
   
except:
 _st_.goboom(_sage_const_72 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_7 , latex(displayStem))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_8 , latex(populations[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_9 , latex(populations[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_10 , latex(populations[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_11 , latex(populations[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_12 , latex(populations[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_13 , latex(populations[_sage_const_5 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_14 , latex(populations[_sage_const_6 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_15 , latex(populations[_sage_const_7 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_16 , latex(populations[_sage_const_8 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_17 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_18 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_19 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_20 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_21 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_89 )
_st_.current_tex_line = _sage_const_91 
_st_.blockbegin()
try:
 moduleNumber="11M"
 problemNumber=_sage_const_53 
 load("../Code/11modelingLogExp/constructHalfLifeModel.sage")
except:
 _st_.goboom(_sage_const_95 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_22 , latex(displayStem))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_23 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_24 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_25 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_26 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_27 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_28 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_110 )
_st_.current_tex_line = _sage_const_112 
_st_.blockbegin()
try:
 moduleNumber="11M"
 problemNumber=_sage_const_54 
 load("../Code/11modelingLogExp/constructTemperatureModel.sage")
except:
 _st_.goboom(_sage_const_116 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_29 , latex(displayStem))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_30 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_31 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_32 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_33 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_34 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_35 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_131 )
_st_.current_tex_line = _sage_const_133 
_st_.blockbegin()
try:
   moduleNumber="11M"
   problemNumber=_sage_const_55 
   load("../Code/11modelingLogExp/identifyModelGraph11.sage")
   
except:
 _st_.goboom(_sage_const_137 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_36 , latex(displayStem))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_37 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_38 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_39 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_40 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_41 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_152 )
_st_.endofdoc()

