## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file /home/archdoc/git-repos/AAG-College-Algebra/buildExams/Module5A.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_41 = Integer(41); _sage_const_64 = Integer(64); _sage_const_63 = Integer(63); _sage_const_46 = Integer(46); _sage_const_87 = Integer(87); _sage_const_81 = Integer(81); _sage_const_68 = Integer(68); _sage_const_83 = Integer(83); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_35 = Integer(35); _sage_const_50 = Integer(50); _sage_const_108 = Integer(108); _sage_const_123 = Integer(123); _sage_const_124 = Integer(124); _sage_const_102 = Integer(102); _sage_const_104 = Integer(104); _sage_const_141 = Integer(141); _sage_const_128 = Integer(128)## This file (Module5A.sagetex.sage) was *autogenerated* from Module5A.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Module5A', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
 load("../Code/generalPurposeMethods.sage")
 load("../Code/keyGeneration.sage")
 load("../Code/commonlyUsedFunctions.sage")
 keyFileName = "Module5"
 version = "A"
except:
 _st_.goboom(_sage_const_41 )
_st_.blockend()
_st_.current_tex_line = _sage_const_46 
_st_.blockbegin()
try:
 moduleNumber="5"
 problemNumber=_sage_const_21 
 load("../Code/05radical/solveRadicalQuadratic.sage")
except:
 _st_.goboom(_sage_const_50 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_0 , latex(displayStem))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_1 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_2 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_3 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_4 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_5 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_6 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_63 )
_st_.current_tex_line = _sage_const_64 
_st_.blockbegin()
try:
 moduleNumber="5"
 problemNumber=_sage_const_22 
 load("../Code/05radical/solveRadicalLinear.sage")
except:
 _st_.goboom(_sage_const_68 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_7 , latex(displayStem))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_8 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_9 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_10 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_11 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_12 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_13 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_81 )
_st_.current_tex_line = _sage_const_83 
_st_.blockbegin()
try:
   moduleNumber="5"
   problemNumber=_sage_const_23 
   load("../Code/05radical/radicalGraphToEquation.sage")
   
except:
 _st_.goboom(_sage_const_87 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_14 , latex(displayStem))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_15 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_16 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_17 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_18 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_19 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_102 )
_st_.current_tex_line = _sage_const_104 
_st_.blockbegin()
try:
 moduleNumber="5"
 problemNumber=_sage_const_24 
 load("../Code/05radical/radicalEquationToGraph.sage")
except:
 _st_.goboom(_sage_const_108 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_123 
 _st_.inline(_sage_const_20 , latex(displayStem))
except:
 _st_.goboom(_sage_const_123 )
try:
 _st_.current_tex_line = _sage_const_123 
 _st_.inline(_sage_const_21 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_123 )
_st_.current_tex_line = _sage_const_124 
_st_.blockbegin()
try:
 moduleNumber="5"
 problemNumber=_sage_const_25 
 load("../Code/05radical/domainRadical.sage")
except:
 _st_.goboom(_sage_const_128 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_22 , latex(displayStem))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_23 , latex(displayProblem))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_24 , latex(choices[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_25 , latex(choices[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_26 , latex(choices[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_27 , latex(choices[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_28 , latex(choices[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_141 )
_st_.endofdoc()

